#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Base classes and interfaces for stream cipher analysis.

This module defines the base architecture for stream cipher analysis, providing
common interfaces and data structures that all cipher implementations inherit from.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from lfsr.attacks import LFSRConfig


@dataclass
class CipherConfig:
    """
    Configuration for a stream cipher.
    
    This class stores the configuration parameters for a stream cipher,
    including key size, IV size, and cipher-specific parameters.
    
    Attributes:
        cipher_name: Name of the cipher (e.g., "A5/1", "E0")
        key_size: Key size in bits
        iv_size: Initialization vector (IV) size in bits
        description: Human-readable description of the cipher
        parameters: Dictionary of cipher-specific parameters
    """
    cipher_name: str
    key_size: int
    iv_size: int
    description: str
    parameters: Dict[str, Any] = field(default_factory=dict)


@dataclass
class CipherStructure:
    """
    Structure information for a stream cipher.
    
    This class describes the internal structure of a cipher, including
    LFSR configurations, clocking mechanisms, and combining functions.
    
    Attributes:
        lfsr_configs: List of LFSR configurations used in the cipher
        clock_control: Description of clocking mechanism
        combiner: Description of combining function
        state_size: Total state size in bits
        details: Additional structure details
    """
    lfsr_configs: List[LFSRConfig]
    clock_control: str
    combiner: str
    state_size: int
    details: Dict[str, Any] = field(default_factory=dict)


@dataclass
class CipherAnalysisResult:
    """
    Results from stream cipher analysis.
    
    This class contains comprehensive analysis results for a stream cipher,
    including structure analysis, keystream properties, and attack results.
    
    Attributes:
        cipher_name: Name of the analyzed cipher
        structure: CipherStructure describing the cipher
        keystream_properties: Properties of generated keystream
        attack_results: Results from applying attacks
        security_assessment: Security assessment and recommendations
        details: Additional analysis details
    """
    cipher_name: str
    structure: CipherStructure
    keystream_properties: Dict[str, Any] = field(default_factory=dict)
    attack_results: Dict[str, Any] = field(default_factory=dict)
    security_assessment: Dict[str, Any] = field(default_factory=dict)
    details: Dict[str, Any] = field(default_factory=dict)


class StreamCipher(ABC):
    """
    Base class for stream cipher analysis.
    
    This abstract base class defines the interface that all stream cipher
    implementations must follow. It provides a consistent API for analyzing
    different ciphers.
    
    **Key Terminology**:
    
    - **Stream Cipher**: A symmetric encryption algorithm that encrypts data
      one bit (or byte) at a time by XORing plaintext with a pseudorandom
      keystream. Stream ciphers are used in many real-world applications.
    
    - **Keystream**: A sequence of pseudorandom bits generated by the cipher
      from a secret key and (optionally) an initialization vector (IV). The
      keystream is XORed with plaintext to produce ciphertext.
    
    - **Key**: A secret value used to initialize the cipher. The key must be
      kept secret and is typically 80-256 bits long depending on the cipher.
    
    - **Initialization Vector (IV)**: A non-secret value used to initialize
      the cipher state. The IV ensures that encrypting the same plaintext with
      the same key produces different ciphertext. Also called "nonce" or
      "frame number" in some contexts.
    
    - **State**: The internal state of the cipher, typically consisting of
      LFSR states, memory elements, and other internal variables. The state
      evolves as the cipher generates keystream.
    
    - **Structure Analysis**: Examining the internal structure of a cipher,
      including LFSR configurations, clocking mechanisms, and combining
      functions. Understanding structure is essential for security analysis.
    
    - **Attack Integration**: Applying cryptanalytic attacks (correlation,
      algebraic, TMTO) to the cipher. This helps assess the cipher's security.
    
    **Subclassing**:
    
    To implement a new cipher, subclass `StreamCipher` and implement:
    
    1. `generate_keystream()`: Generate keystream from key and IV
    2. `analyze_structure()`: Analyze and return cipher structure
    3. `get_config()`: Return cipher configuration
    
    Example:
        >>> class MyCipher(StreamCipher):
        ...     def generate_keystream(self, key, iv, length):
        ...         # Implementation
        ...         pass
        ...     def analyze_structure(self):
        ...         # Implementation
        ...         pass
        ...     def get_config(self):
        ...         # Implementation
        ...         pass
    """
    
    @abstractmethod
    def generate_keystream(
        self,
        key: List[int],
        iv: Optional[List[int]],
        length: int
    ) -> List[int]:
        """
        Generate keystream from key and IV.
        
        This method generates a pseudorandom keystream of the specified length
        using the provided key and initialization vector.
        
        Args:
            key: Secret key as a list of bits (0 or 1)
            iv: Initialization vector as a list of bits (0 or 1), or None
            length: Desired keystream length in bits
        
        Returns:
            List of keystream bits (0 or 1)
        
        Raises:
            ValueError: If key or IV size is incorrect
        """
        pass
    
    @abstractmethod
    def analyze_structure(self) -> CipherStructure:
        """
        Analyze and return cipher structure.
        
        This method analyzes the internal structure of the cipher, including
        LFSR configurations, clocking mechanisms, and combining functions.
        
        Returns:
            CipherStructure describing the cipher's internal structure
        """
        pass
    
    @abstractmethod
    def get_config(self) -> CipherConfig:
        """
        Get cipher configuration.
        
        Returns:
            CipherConfig with cipher parameters
        """
        pass
    
    def apply_attacks(
        self,
        keystream: List[int],
        attack_types: Optional[List[str]] = None
    ) -> Dict[str, Any]:
        """
        Apply available attacks to keystream.
        
        This method applies cryptanalytic attacks (correlation, algebraic, TMTO)
        to the provided keystream. The specific attacks available depend on the
        cipher structure.
        
        Args:
            keystream: Observed keystream bits
            attack_types: List of attack types to apply (None = all available)
        
        Returns:
            Dictionary mapping attack names to results
        """
        # Default implementation: return empty dict
        # Subclasses should override to implement specific attacks
        return {}
    
    def analyze(
        self,
        key: Optional[List[int]] = None,
        iv: Optional[List[int]] = None,
        keystream_length: int = 1000
    ) -> CipherAnalysisResult:
        """
        Perform comprehensive cipher analysis.
        
        This method performs a complete analysis of the cipher, including
        structure analysis, keystream generation, and attack application.
        
        Args:
            key: Optional key for keystream generation (if None, uses default)
            iv: Optional IV for keystream generation (if None, uses default)
            keystream_length: Length of keystream to generate for analysis
        
        Returns:
            CipherAnalysisResult with comprehensive analysis
        """
        # Analyze structure
        structure = self.analyze_structure()
        
        # Generate keystream if key provided
        keystream_properties = {}
        attack_results = {}
        
        if key is not None:
            keystream = self.generate_keystream(key, iv, keystream_length)
            
            # Analyze keystream properties
            keystream_properties = self._analyze_keystream_properties(keystream)
            
            # Apply attacks
            attack_results = self.apply_attacks(keystream)
        
        # Security assessment
        security_assessment = self._assess_security(structure, attack_results)
        
        return CipherAnalysisResult(
            cipher_name=self.get_config().cipher_name,
            structure=structure,
            keystream_properties=keystream_properties,
            attack_results=attack_results,
            security_assessment=security_assessment
        )
    
    def _analyze_keystream_properties(
        self,
        keystream: List[int]
    ) -> Dict[str, Any]:
        """
        Analyze properties of generated keystream.
        
        This helper method analyzes statistical and cryptographic properties
        of the keystream.
        
        Args:
            keystream: Keystream bits to analyze
        
        Returns:
            Dictionary of keystream properties
        """
        if not keystream:
            return {}
        
        # Basic statistics
        ones = sum(keystream)
        zeros = len(keystream) - ones
        
        return {
            'length': len(keystream),
            'ones': ones,
            'zeros': zeros,
            'balance': abs(ones - zeros) / len(keystream) if keystream else 0.0,
            'ones_ratio': ones / len(keystream) if keystream else 0.0
        }
    
    def _assess_security(
        self,
        structure: CipherStructure,
        attack_results: Dict[str, Any]
    ) -> Dict[str, Any]:
        """
        Assess cipher security based on structure and attack results.
        
        This helper method provides a security assessment based on the cipher's
        structure and results from applied attacks.
        
        Args:
            structure: Cipher structure
            attack_results: Results from attacks
        
        Returns:
            Dictionary with security assessment
        """
        return {
            'structure_complexity': 'medium',  # Placeholder
            'known_vulnerabilities': [],
            'recommendations': []
        }
