#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
lfsr-seq - Linear Feedback Shift Register Analysis Tool

This is a wrapper script that calls the modular CLI implementation.
The old monolithic script has been replaced with a clean modular architecture.

Copyright (C) 2023-2025 Mohammadreza Khellat GNU GPL v3+

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 3, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
02111-1307, USA.

See also https://www.gnu.org/licenses/gpl.html
"""

# Import and call the modular CLI implementation
if __name__ == "__main__":
    from lfsr.cli import cli_main

    cli_main()
