#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Unit tests for lfsr.synthesis.

Covers berlekamp_massey, linear_complexity, extract_sequence_from_lfsr,
and synthesize_lfsr_from_sequence.

This is documented in CLAUDE.md as the repo's lowest-coverage file and
the site of a previously-fixed real bug (an unbound polynomial ring
generator `x` never bound to `R.gen()`). All expected outputs below were
independently verified by hand/standalone script before being asserted
here, not assumed from the implementation:

- All-zero sequence [0]*5 over GF(2): the trivial LFSR (poly=1, L=0)
  generates it, since Berlekamp-Massey never sees a discrepancy.
- Single-value sequence [1] over GF(2): shortest LFSR is degree 1,
  connection polynomial x+1.
- The classic maximal-length degree-3 GF(2) m-sequence
  [1,1,0,1,0,0,1] (period 7): the minimal polynomial is x^3+x+1,
  complexity 3 -- and repeating the period-7 sequence 3x must yield
  the identical (poly, complexity), since linear complexity of a
  purely periodic sequence does not grow once a full period (and its
  minimal generating LFSR) has been observed.
- A GF(3) periodic sequence [1,2,0]*3: minimal polynomial x^2+x+1,
  complexity 2 (independently confirmed via Sage's characteristic
  polynomial machinery in a standalone repro).
- extract_sequence_from_lfsr round-trips through
  synthesize_lfsr_from_sequence: feeding a state-update-matrix-driven
  sequence back through Berlekamp-Massey recovers exactly the
  original coefficient vector and correct degree (verified by direct
  script execution against build_state_update_matrix's own output).
"""

import pytest

try:
    from sage.all import *
except ImportError:
    pytest.skip("SageMath not available", allow_module_level=True)

from lfsr.core import build_state_update_matrix
from lfsr.synthesis import (
    berlekamp_massey,
    extract_sequence_from_lfsr,
    linear_complexity,
    synthesize_lfsr_from_sequence,
)


class TestBerlekampMassey:
    def test_empty_sequence_raises_value_error(self):
        with pytest.raises(ValueError, match="Sequence cannot be empty"):
            berlekamp_massey([], 2)

    def test_all_zero_sequence_gf2(self):
        """No discrepancy is ever found, so BM returns the trivial
        polynomial 1 with linear complexity 0."""
        poly, L = berlekamp_massey([0, 0, 0, 0, 0], 2)
        assert L == 0
        assert poly == 1

    def test_single_one_gf2(self):
        """A single nonzero symbol requires a degree-1 LFSR: x + 1."""
        poly, L = berlekamp_massey([1], 2)
        assert L == 1
        R = PolynomialRing(GF(2), "x")
        x = R.gen()
        assert poly == x + 1

    def test_maximal_length_degree3_gf2_sequence(self):
        """Classic m-sequence of period 7 generated by x^3+x+1."""
        seq = [1, 1, 0, 1, 0, 0, 1]
        poly, L = berlekamp_massey(seq, 2)
        assert L == 3
        R = PolynomialRing(GF(2), "x")
        x = R.gen()
        assert poly == x**3 + x + 1

    def test_repeating_full_period_does_not_change_complexity(self):
        """Feeding 3 full periods of the same m-sequence must recover
        the identical minimal polynomial/complexity as a single period,
        since the sequence is fully explained by the degree-3 LFSR
        after the first period."""
        seq = [1, 1, 0, 1, 0, 0, 1] * 3
        poly, L = berlekamp_massey(seq, 2)
        assert L == 3
        R = PolynomialRing(GF(2), "x")
        x = R.gen()
        assert poly == x**3 + x + 1

    def test_gf3_periodic_sequence(self):
        """Independently verified minimal polynomial for [1,2,0]
        repeating over GF(3)."""
        seq = [1, 2, 0, 1, 2, 0, 1, 2, 0]
        poly, L = berlekamp_massey(seq, 3)
        assert L == 2
        R = PolynomialRing(GF(3), "x")
        x = R.gen()
        assert poly == x**2 + x + 1

    def test_returns_sage_polynomial_type(self):
        poly, _ = berlekamp_massey([1, 0, 1], 2)
        R = PolynomialRing(GF(2), "x")
        assert poly.parent() == R

    def test_line_49_early_return_is_unreachable_dead_code(self):
        """berlekamp_massey has `if len(sequence) == 0: raise ...` at
        line 40, then `n = len(s)` (== len(sequence), since `s` is built
        1:1 from `sequence`) followed by `if n == 0: return
        PolynomialRing(F, "x")(1), 0` at line 49. Since line 40 already
        guarantees len(sequence) > 0 for any code that reaches line 47,
        `n` can never independently be 0 there -- this branch is dead
        code, confirmed by exhaustively brute-forcing every sequence of
        length 1-6 over GF(2)/GF(3) with no input reaching it (only the
        already-tested empty-sequence ValueError and the genuine
        BM loop paths were ever hit). Not flagged as a functional bug
        (it doesn't corrupt any real input's result), just documented
        here so line 49's absence from coverage isn't mistaken for an
        untested reachable branch in a future audit."""
        # No assertion beyond documenting: every non-empty sequence
        # already exercised elsewhere in this file takes the normal
        # path, never this branch.
        assert True


class TestLinearComplexity:
    def test_matches_berlekamp_massey_complexity(self):
        seq = [1, 1, 0, 1, 0, 0, 1]
        _, L = berlekamp_massey(seq, 2)
        assert linear_complexity(seq, 2) == L

    def test_all_zero_sequence_has_zero_complexity(self):
        assert linear_complexity([0, 0, 0], 2) == 0

    def test_gf3_sequence_complexity(self):
        assert linear_complexity([1, 2, 0, 1, 2, 0], 3) == 2


class TestExtractSequenceFromLfsr:
    def test_extracts_expected_length(self):
        coeffs = [1, 1, 0, 1]
        C, _ = build_state_update_matrix(coeffs, 2)
        V = VectorSpace(GF(2), 4)
        init = V([1, 0, 0, 0])
        seq = extract_sequence_from_lfsr(C, init, 10)
        assert len(seq) == 10
        assert all(v in (0, 1) for v in seq)

    def test_first_output_matches_initial_state_first_element(self):
        coeffs = [1, 1, 0, 1]
        C, _ = build_state_update_matrix(coeffs, 2)
        V = VectorSpace(GF(2), 4)
        init = V([1, 0, 0, 0])
        seq = extract_sequence_from_lfsr(C, init, 1)
        assert seq == [1]

    def test_zero_length_returns_empty_list(self):
        coeffs = [1, 1, 0, 1]
        C, _ = build_state_update_matrix(coeffs, 2)
        V = VectorSpace(GF(2), 4)
        init = V([1, 0, 0, 0])
        assert extract_sequence_from_lfsr(C, init, 0) == []

    def test_output_values_are_python_ints(self):
        coeffs = [1, 2, 1]
        C, _ = build_state_update_matrix(coeffs, 3)
        V = VectorSpace(GF(3), 3)
        init = V([2, 0, 1])
        seq = extract_sequence_from_lfsr(C, init, 5)
        assert all(isinstance(v, int) for v in seq)


class TestSynthesizeLfsrFromSequence:
    def test_round_trips_original_coefficients(self):
        """A sequence generated by a known 4-bit LFSR, fed back through
        Berlekamp-Massey via synthesize_lfsr_from_sequence, must recover
        the same coefficient vector and complexity equal to the register
        length -- confirmed by direct script execution before writing
        this assertion."""
        coeffs = [1, 1, 0, 1]
        C, _ = build_state_update_matrix(coeffs, 2)
        V = VectorSpace(GF(2), 4)
        init = V([1, 0, 0, 0])
        seq = extract_sequence_from_lfsr(C, init, 10)

        recovered_coeffs, complexity = synthesize_lfsr_from_sequence(seq, 2)
        assert complexity == 4
        assert recovered_coeffs == [1, 1, 0, 1]

    def test_returns_coefficients_of_correct_length(self):
        seq = [1, 1, 0, 1, 0, 0, 1]
        coeffs, complexity = synthesize_lfsr_from_sequence(seq, 2)
        assert len(coeffs) == complexity
        assert complexity == 3

    def test_coefficients_are_python_ints(self):
        seq = [1, 1, 0, 1, 0, 0, 1]
        coeffs, _ = synthesize_lfsr_from_sequence(seq, 2)
        assert all(isinstance(c, int) for c in coeffs)

    def test_trivial_all_zero_sequence_yields_zero_length_coeffs(self):
        coeffs, complexity = synthesize_lfsr_from_sequence([0, 0, 0, 0], 2)
        assert complexity == 0
        assert coeffs == []

    def test_gf3_round_trip(self):
        seq = [1, 2, 0, 1, 2, 0, 1, 2, 0]
        coeffs, complexity = synthesize_lfsr_from_sequence(seq, 3)
        assert complexity == 2
        assert len(coeffs) == 2

    def test_SUSPECTED_REAL_BUG_zero_padding_fabricates_inconsistent_coefficients(self):
        """SUSPECTED REAL BUG in lfsr.synthesis.synthesize_lfsr_from_sequence
        (the zero-padding loop at lines 166-167, `while len(coeffs) <
        complexity: coeffs.append(0)`).

        For the GF(2) sequence [0, 1, 0, 0], berlekamp_massey correctly
        computes connection polynomial `1` (the constant/trivial
        polynomial -- Sage's own `.coefficients(sparse=False)` on it is
        `[1]`, length 1) together with linear complexity L=2. This pairing
        is itself internally inconsistent (a degree-2 linear complexity
        should correspond to a degree-2 connection polynomial, not the
        constant polynomial 1) -- found by exhaustively brute-forcing
        every GF(2) sequence of length 1-6 through berlekamp_massey and
        checking for `len(poly.coefficients(sparse=False)) < complexity`,
        which should never happen for a self-consistent (poly, L) pair.

        synthesize_lfsr_from_sequence does not surface or guard against
        this mismatch: since len(coeffs)=1 < complexity=2, it silently
        zero-pads to `[1, 0]` and reports it as "the" degree-2 LFSR for
        this sequence. But no degree-2 GF(2) LFSR with coefficients
        [1, 0] (nor, checked directly via extract_sequence_from_lfsr
        against build_state_update_matrix([1,0], 2) for all 4 possible
        initial states, any other degree-2 LFSR reachable from this
        polynomial) actually reproduces [0, 1, 0, 0, ...] as a prefix of
        its output for any initial state -- the four trajectories from
        every nonzero/zero initial state are [0,1,0,1,...],
        [1,0,1,0,...], [1,1,1,1,...], and [0,0,0,0,...], none of which
        start with [0, 1, 0, 0]. So the function's returned
        "coefficients" for this input do not actually synthesize an
        LFSR that generates the input sequence, despite that being the
        function's entire documented purpose.

        Root cause is upstream in berlekamp_massey's (L, connection
        polynomial) pairing for this class of sequence, not in the
        zero-padding line itself -- the padding just silently converts
        an already-wrong short polynomial into a plausible-looking but
        equally-wrong full-length coefficient vector instead of
        surfacing the inconsistency. Documented here rather than fixed
        (per instructions not to modify src/), asserting the actual
        (buggy) observed behavior so this test documents rather than
        hides the problem for future triage."""
        coeffs, complexity = synthesize_lfsr_from_sequence([0, 1, 0, 0], 2)

        assert complexity == 2
        # The fabricated, zero-padded (and not sequence-generating)
        # coefficient vector -- this is the actual, buggy output.
        assert coeffs == [1, 0]

        # Independent confirmation that [1, 0] does NOT generate a
        # sequence starting with [0, 1, 0, 0] from any initial state.
        C, _ = build_state_update_matrix(coeffs, 2)
        V = VectorSpace(GF(2), 2)
        target_prefix = [0, 1, 0, 0]
        for a in range(2):
            for b in range(2):
                init = V([a, b])
                observed = extract_sequence_from_lfsr(C, init, 4)
                assert observed != target_prefix
