#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Unit tests for lfsr.synthesis.

Covers berlekamp_massey, linear_complexity, extract_sequence_from_lfsr,
and synthesize_lfsr_from_sequence.

This is documented in CLAUDE.md as the repo's lowest-coverage file and
the site of a previously-fixed real bug (an unbound polynomial ring
generator `x` never bound to `R.gen()`). All expected outputs below were
independently verified by hand/standalone script before being asserted
here, not assumed from the implementation:

- All-zero sequence [0]*5 over GF(2): the trivial LFSR (poly=1, L=0)
  generates it, since Berlekamp-Massey never sees a discrepancy.
- Single-value sequence [1] over GF(2): shortest LFSR is degree 1,
  connection polynomial x+1.
- The classic maximal-length degree-3 GF(2) m-sequence
  [1,1,0,1,0,0,1] (period 7): the minimal polynomial is x^3+x+1,
  complexity 3 -- and repeating the period-7 sequence 3x must yield
  the identical (poly, complexity), since linear complexity of a
  purely periodic sequence does not grow once a full period (and its
  minimal generating LFSR) has been observed.
- A GF(3) periodic sequence [1,2,0]*3: minimal polynomial x^2+x+1,
  complexity 2 (independently confirmed via Sage's characteristic
  polynomial machinery in a standalone repro).
- extract_sequence_from_lfsr round-trips through
  synthesize_lfsr_from_sequence: feeding a state-update-matrix-driven
  sequence back through Berlekamp-Massey recovers exactly the
  original coefficient vector and correct degree (verified by direct
  script execution against build_state_update_matrix's own output).
"""

import pytest

try:
    from sage.all import *
except ImportError:
    pytest.skip("SageMath not available", allow_module_level=True)

from lfsr.core import build_state_update_matrix
from lfsr.synthesis import (
    berlekamp_massey,
    extract_sequence_from_lfsr,
    linear_complexity,
    synthesize_lfsr_from_sequence,
)


class TestBerlekampMassey:
    def test_empty_sequence_raises_value_error(self):
        with pytest.raises(ValueError, match="Sequence cannot be empty"):
            berlekamp_massey([], 2)

    def test_n_zero_after_conversion_is_dead_code(self):
        """SUSPECTED DEAD CODE: berlekamp_massey's second guard,
        `n = len(s); if n == 0: return PolynomialRing(F, "x")(1), 0`
        (synthesis.py line ~48-49), can never trigger for any real
        sequence argument. It runs only after the first guard
        (`if len(sequence) == 0: raise ValueError(...)`) already
        confirmed the input is non-empty, and `s = [F(x) for x in
        sequence]` is a list comprehension that always produces exactly
        len(sequence) elements -- so `n = len(s)` can never differ from
        the already-nonzero len(sequence). Reachable only with a
        sequence-like object whose real iteration yields zero items
        while still reporting nonzero len() -- demonstrated here purely
        to document the branch is dead for genuine sequences, not to
        claim a real-world trigger."""

        class LyingLengthEmptySequence(list):
            def __len__(self):
                return 5  # lies: passes the first `len(sequence) == 0` guard

        seq = LyingLengthEmptySequence()  # real iteration yields 0 items
        poly, L = berlekamp_massey(seq, 2)
        assert L == 0
        assert poly == 1

    def test_all_zero_sequence_gf2(self):
        """No discrepancy is ever found, so BM returns the trivial
        polynomial 1 with linear complexity 0."""
        poly, L = berlekamp_massey([0, 0, 0, 0, 0], 2)
        assert L == 0
        assert poly == 1

    def test_single_one_gf2(self):
        """A single nonzero symbol requires a degree-1 LFSR: x + 1."""
        poly, L = berlekamp_massey([1], 2)
        assert L == 1
        R = PolynomialRing(GF(2), "x")
        x = R.gen()
        assert poly == x + 1

    def test_maximal_length_degree3_gf2_sequence(self):
        """Classic m-sequence of period 7 generated by x^3+x+1."""
        seq = [1, 1, 0, 1, 0, 0, 1]
        poly, L = berlekamp_massey(seq, 2)
        assert L == 3
        R = PolynomialRing(GF(2), "x")
        x = R.gen()
        assert poly == x**3 + x + 1

    def test_repeating_full_period_does_not_change_complexity(self):
        """Feeding 3 full periods of the same m-sequence must recover
        the identical minimal polynomial/complexity as a single period,
        since the sequence is fully explained by the degree-3 LFSR
        after the first period."""
        seq = [1, 1, 0, 1, 0, 0, 1] * 3
        poly, L = berlekamp_massey(seq, 2)
        assert L == 3
        R = PolynomialRing(GF(2), "x")
        x = R.gen()
        assert poly == x**3 + x + 1

    def test_gf3_periodic_sequence(self):
        """Independently verified minimal polynomial for [1,2,0]
        repeating over GF(3)."""
        seq = [1, 2, 0, 1, 2, 0, 1, 2, 0]
        poly, L = berlekamp_massey(seq, 3)
        assert L == 2
        R = PolynomialRing(GF(3), "x")
        x = R.gen()
        assert poly == x**2 + x + 1

    def test_returns_sage_polynomial_type(self):
        poly, _ = berlekamp_massey([1, 0, 1], 2)
        R = PolynomialRing(GF(2), "x")
        assert poly.parent() == R

    def test_line_49_early_return_is_unreachable_dead_code(self):
        """berlekamp_massey has `if len(sequence) == 0: raise ...` at
        line 40, then `n = len(s)` (== len(sequence), since `s` is built
        1:1 from `sequence`) followed by `if n == 0: return
        PolynomialRing(F, "x")(1), 0` at line 49. Since line 40 already
        guarantees len(sequence) > 0 for any code that reaches line 47,
        `n` can never independently be 0 there -- this branch is dead
        code, confirmed by exhaustively brute-forcing every sequence of
        length 1-6 over GF(2)/GF(3) with no input reaching it (only the
        already-tested empty-sequence ValueError and the genuine
        BM loop paths were ever hit). Not flagged as a functional bug
        (it doesn't corrupt any real input's result), just documented
        here so line 49's absence from coverage isn't mistaken for an
        untested reachable branch in a future audit."""
        # No assertion beyond documenting: every non-empty sequence
        # already exercised elsewhere in this file takes the normal
        # path, never this branch.
        assert True


class TestLinearComplexity:
    def test_matches_berlekamp_massey_complexity(self):
        seq = [1, 1, 0, 1, 0, 0, 1]
        _, L = berlekamp_massey(seq, 2)
        assert linear_complexity(seq, 2) == L

    def test_all_zero_sequence_has_zero_complexity(self):
        assert linear_complexity([0, 0, 0], 2) == 0

    def test_gf3_sequence_complexity(self):
        assert linear_complexity([1, 2, 0, 1, 2, 0], 3) == 2


class TestExtractSequenceFromLfsr:
    def test_extracts_expected_length(self):
        coeffs = [1, 1, 0, 1]
        C, _ = build_state_update_matrix(coeffs, 2)
        V = VectorSpace(GF(2), 4)
        init = V([1, 0, 0, 0])
        seq = extract_sequence_from_lfsr(C, init, 10)
        assert len(seq) == 10
        assert all(v in (0, 1) for v in seq)

    def test_first_output_matches_initial_state_first_element(self):
        coeffs = [1, 1, 0, 1]
        C, _ = build_state_update_matrix(coeffs, 2)
        V = VectorSpace(GF(2), 4)
        init = V([1, 0, 0, 0])
        seq = extract_sequence_from_lfsr(C, init, 1)
        assert seq == [1]

    def test_zero_length_returns_empty_list(self):
        coeffs = [1, 1, 0, 1]
        C, _ = build_state_update_matrix(coeffs, 2)
        V = VectorSpace(GF(2), 4)
        init = V([1, 0, 0, 0])
        assert extract_sequence_from_lfsr(C, init, 0) == []

    def test_output_values_are_python_ints(self):
        coeffs = [1, 2, 1]
        C, _ = build_state_update_matrix(coeffs, 3)
        V = VectorSpace(GF(3), 3)
        init = V([2, 0, 1])
        seq = extract_sequence_from_lfsr(C, init, 5)
        assert all(isinstance(v, int) for v in seq)


class TestSynthesizeLfsrFromSequence:
    def test_round_trips_original_coefficients(self):
        """A sequence generated by a known 4-bit LFSR, fed back through
        Berlekamp-Massey via synthesize_lfsr_from_sequence, must recover
        the same coefficient vector and complexity equal to the register
        length -- confirmed by direct script execution before writing
        this assertion."""
        coeffs = [1, 1, 0, 1]
        C, _ = build_state_update_matrix(coeffs, 2)
        V = VectorSpace(GF(2), 4)
        init = V([1, 0, 0, 0])
        seq = extract_sequence_from_lfsr(C, init, 10)

        recovered_coeffs, complexity = synthesize_lfsr_from_sequence(seq, 2)
        assert complexity == 4
        assert recovered_coeffs == [1, 1, 0, 1]

    def test_returns_coefficients_of_correct_length(self):
        seq = [1, 1, 0, 1, 0, 0, 1]
        coeffs, complexity = synthesize_lfsr_from_sequence(seq, 2)
        assert len(coeffs) == complexity
        assert complexity == 3

    def test_coefficients_are_python_ints(self):
        seq = [1, 1, 0, 1, 0, 0, 1]
        coeffs, _ = synthesize_lfsr_from_sequence(seq, 2)
        assert all(isinstance(c, int) for c in coeffs)

    def test_trivial_all_zero_sequence_yields_zero_length_coeffs(self):
        coeffs, complexity = synthesize_lfsr_from_sequence([0, 0, 0, 0], 2)
        assert complexity == 0
        assert coeffs == []

    def test_gf3_round_trip(self):
        """GF(3) exercises the sign-negation step (non-trivial since -1
        mod 3 != -1 mod 2), which GF(2)-only regression tests cannot
        distinguish from a plain reversal."""
        coeffs = [2, 1]
        C, _ = build_state_update_matrix(coeffs, 3)
        V = VectorSpace(GF(3), 2)
        init = V([1, 0])
        seq = extract_sequence_from_lfsr(C, init, 9)

        recovered_coeffs, complexity = synthesize_lfsr_from_sequence(seq, 3)
        assert complexity == 2
        assert recovered_coeffs == [2, 1]

    def test_short_degree_polynomial_reconstructs_correctly(self):
        """Regression test for a fixed bug in
        lfsr.synthesis.synthesize_lfsr_from_sequence.

        For the GF(2) sequence [0, 1, 0, 0], berlekamp_massey computes
        connection polynomial `1` (Sage's `.coefficients(sparse=False)`
        on it is `[1]`, length 1 -- Sage drops trailing zero
        coefficients) together with linear complexity L=2; this is a
        genuinely valid (poly, L) pair, since the polynomial's degree
        need not equal L exactly once high-order taps are all zero.

        The old code built the returned coefficient vector as
        `poly.coefficients(sparse=False)[:complexity]` zero-padded at
        the end -- which conflates the connection polynomial's raw
        low-to-high coefficient order with build_state_update_matrix's
        expected tap order (oldest-sample-first, negated, with the
        constant term dropped). For this input that produced [1, 0],
        which does not reproduce [0, 1, 0, 0] from any initial state.

        Fixed by: padding the raw coefficients to length complexity + 1
        with trailing zeros first, then dropping the constant term,
        negating (mod gf_order) and reversing the rest. This test
        confirms the corrected coefficients ([0, 0], the all-zero
        length-2 LFSR) actually reproduce the sequence, and that the
        reconstructed LFSR round-trips end-to-end via
        build_state_update_matrix/extract_sequence_from_lfsr."""
        coeffs, complexity = synthesize_lfsr_from_sequence([0, 1, 0, 0], 2)

        assert complexity == 2
        assert coeffs == [0, 0]

        C, _ = build_state_update_matrix(coeffs, 2)
        V = VectorSpace(GF(2), 2)
        target_prefix = [0, 1, 0, 0]
        init = V([0, 1])
        observed = extract_sequence_from_lfsr(C, init, 4)
        assert observed == target_prefix
